[2023-09-19T10:09:22.644+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.extract_data manual__2023-09-19T10:09:21.491994+00:00 [queued]>
[2023-09-19T10:09:22.648+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.extract_data manual__2023-09-19T10:09:21.491994+00:00 [queued]>
[2023-09-19T10:09:22.648+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T10:09:22.654+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonVirtualenvOperator): extract_data> on 2023-09-19 10:09:21.491994+00:00
[2023-09-19T10:09:22.659+0000] {standard_task_runner.py:57} INFO - Started process 1259 to run task
[2023-09-19T10:09:22.662+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'extract_data', 'manual__2023-09-19T10:09:21.491994+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp7b_l6w3m']
[2023-09-19T10:09:22.662+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask extract_data
[2023-09-19T10:09:22.692+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data.extract_data manual__2023-09-19T10:09:21.491994+00:00 [running]> on host 12ae14f8feaf
[2023-09-19T10:09:22.734+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T10:09:21.491994+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T10:09:21.491994+00:00'
[2023-09-19T10:09:22.737+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvhd_dnfuh --system-site-packages
[2023-09-19T10:09:22.744+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T10:09:23.361+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 168ms
[2023-09-19T10:09:23.361+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvhd_dnfuh, clear=False, no_vcs_ignore=False, global=True)
[2023-09-19T10:09:23.362+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-09-19T10:09:23.362+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.2, setuptools==68.0.0, wheel==0.40.0
[2023-09-19T10:09:23.362+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-09-19T10:09:23.384+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvhd_dnfuh/bin/pip install -r /tmp/venvhd_dnfuh/requirements.txt
[2023-09-19T10:09:23.391+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T10:09:27.118+0000] {process_utils.py:190} INFO - 
[2023-09-19T10:09:27.119+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2 -> 23.2.1
[2023-09-19T10:09:27.119+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-09-19T10:09:27.188+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvhd_dnfuh/bin/python /tmp/venvhd_dnfuh/script.py /tmp/venvhd_dnfuh/script.in /tmp/venvhd_dnfuh/script.out /tmp/venvhd_dnfuh/string_args.txt /tmp/venvhd_dnfuh/termination.log
[2023-09-19T10:09:27.194+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T10:09:27.936+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2023-09-19T10:09:27.936+0000] {process_utils.py:190} INFO -   File "/tmp/venvhd_dnfuh/script.py", line 46, in <module>
[2023-09-19T10:09:27.936+0000] {process_utils.py:190} INFO -     res = download_data(*arg_dict["args"], **arg_dict["kwargs"])
[2023-09-19T10:09:27.937+0000] {process_utils.py:190} INFO -   File "/tmp/venvhd_dnfuh/script.py", line 28, in download_data
[2023-09-19T10:09:27.937+0000] {process_utils.py:190} INFO -     logging.basicConfig(
[2023-09-19T10:09:27.937+0000] {process_utils.py:190} INFO - NameError: name 'logging' is not defined
[2023-09-19T10:09:28.036+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 602, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 463, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'logging' is not defined
[2023-09-19T10:09:28.039+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=weather_data, task_id=extract_data, execution_date=20230919T100921, start_date=20230919T100922, end_date=20230919T100928
[2023-09-19T10:09:28.047+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 79 for task extract_data (Process returned non-zero exit status 1.
name 'logging' is not defined; 1259)
[2023-09-19T10:09:28.063+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T10:09:28.077+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
