[2023-09-19T10:01:01.030+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.create_chart manual__2023-09-19T10:00:58.372311+00:00 [queued]>
[2023-09-19T10:01:01.035+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.create_chart manual__2023-09-19T10:00:58.372311+00:00 [queued]>
[2023-09-19T10:01:01.035+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T10:01:01.042+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonVirtualenvOperator): create_chart> on 2023-09-19 10:00:58.372311+00:00
[2023-09-19T10:01:01.047+0000] {standard_task_runner.py:57} INFO - Started process 1083 to run task
[2023-09-19T10:01:01.050+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'create_chart', 'manual__2023-09-19T10:00:58.372311+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpo9r4415b']
[2023-09-19T10:01:01.051+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask create_chart
[2023-09-19T10:01:01.080+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data.create_chart manual__2023-09-19T10:00:58.372311+00:00 [running]> on host 12ae14f8feaf
[2023-09-19T10:01:01.120+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='create_chart' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T10:00:58.372311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T10:00:58.372311+00:00'
[2023-09-19T10:01:01.123+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv_6bdhe2w --system-site-packages
[2023-09-19T10:01:01.130+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T10:01:01.745+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 168ms
[2023-09-19T10:01:01.746+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv_6bdhe2w, clear=False, no_vcs_ignore=False, global=True)
[2023-09-19T10:01:01.746+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-09-19T10:01:01.746+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.2, setuptools==68.0.0, wheel==0.40.0
[2023-09-19T10:01:01.747+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-09-19T10:01:01.769+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv_6bdhe2w/bin/pip install -r /tmp/venv_6bdhe2w/requirements.txt
[2023-09-19T10:01:01.776+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T10:01:02.741+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv_6bdhe2w/requirements.txt (line 1)) (2.0.3)
[2023-09-19T10:01:03.037+0000] {process_utils.py:190} INFO - Collecting matplotlib (from -r /tmp/venv_6bdhe2w/requirements.txt (line 2))
[2023-09-19T10:01:03.037+0000] {process_utils.py:190} INFO -   Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/84/76/9267af394cb88ce5245b5a9d328ee90ccd5710a1d08b0ec363c3a86cd992/matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T10:01:03.038+0000] {process_utils.py:190} INFO -   Using cached matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.7 kB)
[2023-09-19T10:01:03.083+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv_6bdhe2w/requirements.txt (line 1)) (2.8.2)
[2023-09-19T10:01:03.083+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv_6bdhe2w/requirements.txt (line 1)) (2023.3)
[2023-09-19T10:01:03.084+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv_6bdhe2w/requirements.txt (line 1)) (2023.3)
[2023-09-19T10:01:03.084+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy>=1.20.3 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv_6bdhe2w/requirements.txt (line 1)) (1.24.4)
[2023-09-19T10:01:03.192+0000] {process_utils.py:190} INFO - Collecting contourpy>=1.0.1 (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2))
[2023-09-19T10:01:03.193+0000] {process_utils.py:190} INFO -   Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/9b/cb/08f884c4c2efd433a38876b1b8069bfecef3f2d21ff0ce635d455962f70f/contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T10:01:03.193+0000] {process_utils.py:190} INFO -   Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.9 kB)
[2023-09-19T10:01:03.247+0000] {process_utils.py:190} INFO - Collecting cycler>=0.10 (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2))
[2023-09-19T10:01:03.248+0000] {process_utils.py:190} INFO -   Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
[2023-09-19T10:01:03.348+0000] {process_utils.py:190} INFO - Collecting fonttools>=4.22.0 (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2))
[2023-09-19T10:01:03.348+0000] {process_utils.py:190} INFO -   Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/61/3f/68c99c2b5fb29f42ba22027d035ae08f0b2ea0178fbf00e7cef730b1a809/fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T10:01:03.349+0000] {process_utils.py:190} INFO -   Using cached fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (150 kB)
[2023-09-19T10:01:03.437+0000] {process_utils.py:190} INFO - Collecting kiwisolver>=1.0.1 (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2))
[2023-09-19T10:01:03.438+0000] {process_utils.py:190} INFO -   Obtaining dependency information for kiwisolver>=1.0.1 from https://files.pythonhosted.org/packages/10/15/0c225864a00eb3dbd3d04b6465f331dc12a6e80673449166457b9566036d/kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T10:01:03.438+0000] {process_utils.py:190} INFO -   Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.4 kB)
[2023-09-19T10:01:03.439+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging>=20.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2)) (23.1)
[2023-09-19T10:01:03.664+0000] {process_utils.py:190} INFO - Collecting pillow>=6.2.0 (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2))
[2023-09-19T10:01:03.664+0000] {process_utils.py:190} INFO -   Obtaining dependency information for pillow>=6.2.0 from https://files.pythonhosted.org/packages/2e/17/f19ad27effaf9b1ce6fe88d9f238d430293c486e33fdac71f037153cfd37/Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl.metadata
[2023-09-19T10:01:03.665+0000] {process_utils.py:190} INFO -   Using cached Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl.metadata (9.5 kB)
[2023-09-19T10:01:03.666+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2)) (3.1.1)
[2023-09-19T10:01:03.667+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources>=3.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2)) (6.0.1)
[2023-09-19T10:01:03.705+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=3.1.0 in /home/***/.local/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib->-r /tmp/venv_6bdhe2w/requirements.txt (line 2)) (3.16.2)
[2023-09-19T10:01:03.718+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venv_6bdhe2w/requirements.txt (line 1)) (1.16.0)
[2023-09-19T10:01:03.756+0000] {process_utils.py:190} INFO - Using cached matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.4 MB)
[2023-09-19T10:01:03.772+0000] {process_utils.py:190} INFO - Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (285 kB)
[2023-09-19T10:01:03.781+0000] {process_utils.py:190} INFO - Using cached fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.5 MB)
[2023-09-19T10:01:03.788+0000] {process_utils.py:190} INFO - Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.4 MB)
[2023-09-19T10:01:03.792+0000] {process_utils.py:190} INFO - Using cached Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl (3.5 MB)
[2023-09-19T10:01:06.249+0000] {process_utils.py:190} INFO - Installing collected packages: pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
[2023-09-19T10:01:07.906+0000] {process_utils.py:190} INFO - Successfully installed contourpy-1.1.1 cycler-0.11.0 fonttools-4.42.1 kiwisolver-1.4.5 matplotlib-3.7.3 pillow-10.0.1
[2023-09-19T10:01:08.089+0000] {process_utils.py:190} INFO - 
[2023-09-19T10:01:08.090+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2 -> 23.2.1
[2023-09-19T10:01:08.090+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-09-19T10:01:08.217+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv_6bdhe2w/bin/python /tmp/venv_6bdhe2w/script.py /tmp/venv_6bdhe2w/script.in /tmp/venv_6bdhe2w/script.out /tmp/venv_6bdhe2w/string_args.txt /tmp/venv_6bdhe2w/termination.log
[2023-09-19T10:01:08.224+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T10:01:09.342+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2023-09-19T10:01:09.343+0000] {process_utils.py:190} INFO -   File "/tmp/venv_6bdhe2w/script.py", line 52, in <module>
[2023-09-19T10:01:09.343+0000] {process_utils.py:190} INFO -     res = chart(*arg_dict["args"], **arg_dict["kwargs"])
[2023-09-19T10:01:09.343+0000] {process_utils.py:190} INFO -   File "/tmp/venv_6bdhe2w/script.py", line 30, in chart
[2023-09-19T10:01:09.344+0000] {process_utils.py:190} INFO -     df = pd.read_csv('../files/weather.csv')
[2023-09-19T10:01:09.344+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
[2023-09-19T10:01:09.344+0000] {process_utils.py:190} INFO -     return _read(filepath_or_buffer, kwds)
[2023-09-19T10:01:09.344+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
[2023-09-19T10:01:09.345+0000] {process_utils.py:190} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-09-19T10:01:09.345+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
[2023-09-19T10:01:09.345+0000] {process_utils.py:190} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-09-19T10:01:09.345+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
[2023-09-19T10:01:09.346+0000] {process_utils.py:190} INFO -     self.handles = get_handle(
[2023-09-19T10:01:09.346+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
[2023-09-19T10:01:09.346+0000] {process_utils.py:190} INFO -     handle = open(
[2023-09-19T10:01:09.346+0000] {process_utils.py:190} INFO - FileNotFoundError: [Errno 2] No such file or directory: '../files/weather.csv'
[2023-09-19T10:01:09.525+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 602, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 463, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '../files/weather.csv'
[2023-09-19T10:01:09.528+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=weather_data, task_id=create_chart, execution_date=20230919T100058, start_date=20230919T100101, end_date=20230919T100109
[2023-09-19T10:01:09.535+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 76 for task create_chart (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '../files/weather.csv'; 1083)
[2023-09-19T10:01:09.580+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T10:01:09.589+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
