[2023-09-20T07:15:56.980+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.create_chart manual__2023-09-20T07:15:54.082297+00:00 [queued]>
[2023-09-20T07:15:56.984+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.create_chart manual__2023-09-20T07:15:54.082297+00:00 [queued]>
[2023-09-20T07:15:56.984+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T07:15:56.990+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonVirtualenvOperator): create_chart> on 2023-09-20 07:15:54.082297+00:00
[2023-09-20T07:15:56.995+0000] {standard_task_runner.py:57} INFO - Started process 3276 to run task
[2023-09-20T07:15:56.997+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'create_chart', 'manual__2023-09-20T07:15:54.082297+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpj3qkt3bb']
[2023-09-20T07:15:56.998+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask create_chart
[2023-09-20T07:15:57.027+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data.create_chart manual__2023-09-20T07:15:54.082297+00:00 [running]> on host 90bb52186339
[2023-09-20T07:15:57.064+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='create_chart' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T07:15:54.082297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T07:15:54.082297+00:00'
[2023-09-20T07:15:57.066+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvpwu0cwya --system-site-packages
[2023-09-20T07:15:57.074+0000] {process_utils.py:186} INFO - Output:
[2023-09-20T07:15:57.623+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 151ms
[2023-09-20T07:15:57.624+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvpwu0cwya, clear=False, no_vcs_ignore=False, global=True)
[2023-09-20T07:15:57.624+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-09-20T07:15:57.624+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.2, setuptools==68.0.0, wheel==0.40.0
[2023-09-20T07:15:57.625+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-09-20T07:15:57.644+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvpwu0cwya/bin/pip install -r /tmp/venvpwu0cwya/requirements.txt
[2023-09-20T07:15:57.651+0000] {process_utils.py:186} INFO - Output:
[2023-09-20T07:15:58.550+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvpwu0cwya/requirements.txt (line 1)) (2.0.3)
[2023-09-20T07:15:58.825+0000] {process_utils.py:190} INFO - Collecting matplotlib (from -r /tmp/venvpwu0cwya/requirements.txt (line 2))
[2023-09-20T07:15:58.825+0000] {process_utils.py:190} INFO -   Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/84/76/9267af394cb88ce5245b5a9d328ee90ccd5710a1d08b0ec363c3a86cd992/matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-20T07:15:58.826+0000] {process_utils.py:190} INFO -   Using cached matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.7 kB)
[2023-09-20T07:15:58.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvpwu0cwya/requirements.txt (line 1)) (2.8.2)
[2023-09-20T07:15:58.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvpwu0cwya/requirements.txt (line 1)) (2023.3)
[2023-09-20T07:15:58.865+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvpwu0cwya/requirements.txt (line 1)) (2023.3)
[2023-09-20T07:15:58.865+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy>=1.20.3 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvpwu0cwya/requirements.txt (line 1)) (1.24.4)
[2023-09-20T07:15:58.971+0000] {process_utils.py:190} INFO - Collecting contourpy>=1.0.1 (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2))
[2023-09-20T07:15:58.971+0000] {process_utils.py:190} INFO -   Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/9b/cb/08f884c4c2efd433a38876b1b8069bfecef3f2d21ff0ce635d455962f70f/contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-20T07:15:58.972+0000] {process_utils.py:190} INFO -   Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.9 kB)
[2023-09-20T07:15:59.025+0000] {process_utils.py:190} INFO - Collecting cycler>=0.10 (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2))
[2023-09-20T07:15:59.027+0000] {process_utils.py:190} INFO -   Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
[2023-09-20T07:15:59.122+0000] {process_utils.py:190} INFO - Collecting fonttools>=4.22.0 (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2))
[2023-09-20T07:15:59.122+0000] {process_utils.py:190} INFO -   Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/61/3f/68c99c2b5fb29f42ba22027d035ae08f0b2ea0178fbf00e7cef730b1a809/fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-20T07:15:59.123+0000] {process_utils.py:190} INFO -   Using cached fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (150 kB)
[2023-09-20T07:15:59.209+0000] {process_utils.py:190} INFO - Collecting kiwisolver>=1.0.1 (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2))
[2023-09-20T07:15:59.209+0000] {process_utils.py:190} INFO -   Obtaining dependency information for kiwisolver>=1.0.1 from https://files.pythonhosted.org/packages/10/15/0c225864a00eb3dbd3d04b6465f331dc12a6e80673449166457b9566036d/kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-20T07:15:59.210+0000] {process_utils.py:190} INFO -   Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.4 kB)
[2023-09-20T07:15:59.211+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging>=20.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2)) (23.1)
[2023-09-20T07:15:59.412+0000] {process_utils.py:190} INFO - Collecting pillow>=6.2.0 (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2))
[2023-09-20T07:15:59.413+0000] {process_utils.py:190} INFO -   Obtaining dependency information for pillow>=6.2.0 from https://files.pythonhosted.org/packages/2e/17/f19ad27effaf9b1ce6fe88d9f238d430293c486e33fdac71f037153cfd37/Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl.metadata
[2023-09-20T07:15:59.413+0000] {process_utils.py:190} INFO -   Using cached Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl.metadata (9.5 kB)
[2023-09-20T07:15:59.414+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2)) (3.1.1)
[2023-09-20T07:15:59.415+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources>=3.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2)) (6.0.1)
[2023-09-20T07:15:59.447+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=3.1.0 in /home/***/.local/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib->-r /tmp/venvpwu0cwya/requirements.txt (line 2)) (3.16.2)
[2023-09-20T07:15:59.458+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvpwu0cwya/requirements.txt (line 1)) (1.16.0)
[2023-09-20T07:15:59.492+0000] {process_utils.py:190} INFO - Using cached matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.4 MB)
[2023-09-20T07:15:59.507+0000] {process_utils.py:190} INFO - Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (285 kB)
[2023-09-20T07:15:59.516+0000] {process_utils.py:190} INFO - Using cached fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.5 MB)
[2023-09-20T07:15:59.522+0000] {process_utils.py:190} INFO - Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.4 MB)
[2023-09-20T07:15:59.526+0000] {process_utils.py:190} INFO - Using cached Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl (3.5 MB)
[2023-09-20T07:16:01.724+0000] {process_utils.py:190} INFO - Installing collected packages: pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
[2023-09-20T07:16:03.239+0000] {process_utils.py:190} INFO - Successfully installed contourpy-1.1.1 cycler-0.11.0 fonttools-4.42.1 kiwisolver-1.4.5 matplotlib-3.7.3 pillow-10.0.1
[2023-09-20T07:16:03.430+0000] {process_utils.py:190} INFO - 
[2023-09-20T07:16:03.431+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2 -> 23.2.1
[2023-09-20T07:16:03.431+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-09-20T07:16:03.551+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvpwu0cwya/bin/python /tmp/venvpwu0cwya/script.py /tmp/venvpwu0cwya/script.in /tmp/venvpwu0cwya/script.out /tmp/venvpwu0cwya/string_args.txt /tmp/venvpwu0cwya/termination.log
[2023-09-20T07:16:03.558+0000] {process_utils.py:186} INFO - Output:
[2023-09-20T07:16:04.593+0000] {process_utils.py:190} INFO - [[34m2023-09-20T07:16:04.592+0000[0m] {[34mcategory.py:[0m223} INFO[0m - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.[0m
[2023-09-20T07:16:04.594+0000] {process_utils.py:190} INFO - [[34m2023-09-20T07:16:04.593+0000[0m] {[34mcategory.py:[0m223} INFO[0m - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.[0m
[2023-09-20T07:16:04.594+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2023-09-20T07:16:04.594+0000] {process_utils.py:190} INFO -   File "/tmp/venvpwu0cwya/script.py", line 57, in <module>
[2023-09-20T07:16:04.594+0000] {process_utils.py:190} INFO -     res = create_chart(*arg_dict["args"], **arg_dict["kwargs"])
[2023-09-20T07:16:04.595+0000] {process_utils.py:190} INFO -   File "/tmp/venvpwu0cwya/script.py", line 42, in create_chart
[2023-09-20T07:16:04.595+0000] {process_utils.py:190} INFO -     plt.plot.xaxis.set_major_locator(locator)
[2023-09-20T07:16:04.595+0000] {process_utils.py:190} INFO - AttributeError: 'function' object has no attribute 'xaxis'
[2023-09-20T07:16:04.769+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 602, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 463, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
'function' object has no attribute 'xaxis'
[2023-09-20T07:16:04.772+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=weather_data, task_id=create_chart, execution_date=20230920T071554, start_date=20230920T071556, end_date=20230920T071604
[2023-09-20T07:16:04.781+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 87 for task create_chart (Process returned non-zero exit status 1.
'function' object has no attribute 'xaxis'; 3276)
[2023-09-20T07:16:04.805+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T07:16:04.816+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
