[2023-09-19T07:00:57.246+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.extract_data manual__2023-09-19T07:00:56.039871+00:00 [queued]>
[2023-09-19T07:00:57.251+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.extract_data manual__2023-09-19T07:00:56.039871+00:00 [queued]>
[2023-09-19T07:00:57.252+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T07:00:57.258+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonVirtualenvOperator): extract_data> on 2023-09-19 07:00:56.039871+00:00
[2023-09-19T07:00:57.263+0000] {standard_task_runner.py:57} INFO - Started process 4370 to run task
[2023-09-19T07:00:57.266+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'extract_data', 'manual__2023-09-19T07:00:56.039871+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpqko6mn6i']
[2023-09-19T07:00:57.267+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask extract_data
[2023-09-19T07:00:57.304+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data.extract_data manual__2023-09-19T07:00:56.039871+00:00 [running]> on host 973481dcacb6
[2023-09-19T07:00:57.353+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T07:00:56.039871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T07:00:56.039871+00:00'
[2023-09-19T07:00:57.356+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvr_s49ypj --system-site-packages
[2023-09-19T07:00:57.364+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T07:00:58.181+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 309ms
[2023-09-19T07:00:58.181+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvr_s49ypj, clear=False, no_vcs_ignore=False, global=True)
[2023-09-19T07:00:58.182+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-09-19T07:00:58.182+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.2, setuptools==68.0.0, wheel==0.40.0
[2023-09-19T07:00:58.182+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-09-19T07:00:58.210+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvr_s49ypj/bin/pip install -r /tmp/venvr_s49ypj/requirements.txt
[2023-09-19T07:00:58.217+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T07:00:59.611+0000] {process_utils.py:190} INFO - Collecting *** (from -r /tmp/venvr_s49ypj/requirements.txt (line 1))
[2023-09-19T07:00:59.766+0000] {process_utils.py:190} INFO -   Downloading ***-0.6.tar.gz (1.2 kB)
[2023-09-19T07:00:59.771+0000] {process_utils.py:190} INFO -   Preparing metadata (setup.py): started
[2023-09-19T07:01:00.200+0000] {process_utils.py:190} INFO -   Preparing metadata (setup.py): finished with status 'error'
[2023-09-19T07:01:00.204+0000] {process_utils.py:190} INFO -   error: subprocess-exited-with-error
[2023-09-19T07:01:00.204+0000] {process_utils.py:190} INFO - 
[2023-09-19T07:01:00.204+0000] {process_utils.py:190} INFO -   × python setup.py egg_info did not run successfully.
[2023-09-19T07:01:00.204+0000] {process_utils.py:190} INFO -   │ exit code: 1
[2023-09-19T07:01:00.205+0000] {process_utils.py:190} INFO -   ╰─> [14 lines of output]
[2023-09-19T07:01:00.205+0000] {process_utils.py:190} INFO -       running egg_info
[2023-09-19T07:01:00.205+0000] {process_utils.py:190} INFO -       creating /tmp/pip-pip-egg-info-auwfz6ih/***.egg-info
[2023-09-19T07:01:00.205+0000] {process_utils.py:190} INFO -       writing /tmp/pip-pip-egg-info-auwfz6ih/***.egg-info/PKG-INFO
[2023-09-19T07:01:00.206+0000] {process_utils.py:190} INFO -       writing dependency_links to /tmp/pip-pip-egg-info-auwfz6ih/***.egg-info/dependency_links.txt
[2023-09-19T07:01:00.206+0000] {process_utils.py:190} INFO -       writing top-level names to /tmp/pip-pip-egg-info-auwfz6ih/***.egg-info/top_level.txt
[2023-09-19T07:01:00.206+0000] {process_utils.py:190} INFO -       writing manifest file '/tmp/pip-pip-egg-info-auwfz6ih/***.egg-info/SOURCES.txt'
[2023-09-19T07:01:00.206+0000] {process_utils.py:190} INFO -       reading manifest file '/tmp/pip-pip-egg-info-auwfz6ih/***.egg-info/SOURCES.txt'
[2023-09-19T07:01:00.207+0000] {process_utils.py:190} INFO -       writing manifest file '/tmp/pip-pip-egg-info-auwfz6ih/***.egg-info/SOURCES.txt'
[2023-09-19T07:01:00.207+0000] {process_utils.py:190} INFO -       Traceback (most recent call last):
[2023-09-19T07:01:00.207+0000] {process_utils.py:190} INFO -         File "<string>", line 2, in <module>
[2023-09-19T07:01:00.207+0000] {process_utils.py:190} INFO -         File "<pip-setuptools-caller>", line 34, in <module>
[2023-09-19T07:01:00.207+0000] {process_utils.py:190} INFO -         File "/tmp/pip-install-yjr6io0o/***_83716ed31b06410b982619619e64f869/setup.py", line 32, in <module>
[2023-09-19T07:01:00.208+0000] {process_utils.py:190} INFO -           raise RuntimeError('Please install package apache-*** instead of ***')
[2023-09-19T07:01:00.208+0000] {process_utils.py:190} INFO -       RuntimeError: Please install package apache-*** instead of ***
[2023-09-19T07:01:00.208+0000] {process_utils.py:190} INFO -       [end of output]
[2023-09-19T07:01:00.208+0000] {process_utils.py:190} INFO - 
[2023-09-19T07:01:00.209+0000] {process_utils.py:190} INFO -   note: This error originates from a subprocess, and is likely not a problem with pip.
[2023-09-19T07:01:00.209+0000] {process_utils.py:190} INFO - error: metadata-generation-failed
[2023-09-19T07:01:00.209+0000] {process_utils.py:190} INFO - 
[2023-09-19T07:01:00.210+0000] {process_utils.py:190} INFO - × Encountered error while generating package metadata.
[2023-09-19T07:01:00.210+0000] {process_utils.py:190} INFO - ╰─> See above for output.
[2023-09-19T07:01:00.210+0000] {process_utils.py:190} INFO - 
[2023-09-19T07:01:00.211+0000] {process_utils.py:190} INFO - note: This is an issue with the package mentioned above, not pip.
[2023-09-19T07:01:00.211+0000] {process_utils.py:190} INFO - hint: See above for details.
[2023-09-19T07:01:00.407+0000] {process_utils.py:190} INFO - 
[2023-09-19T07:01:00.408+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2 -> 23.2.1
[2023-09-19T07:01:00.408+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-09-19T07:01:00.483+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 594, in execute_callable
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/python_virtualenv.py", line 100, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvr_s49ypj/bin/pip', 'install', '-r', '/tmp/venvr_s49ypj/requirements.txt']' returned non-zero exit status 1.
[2023-09-19T07:01:00.493+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=weather_data, task_id=extract_data, execution_date=20230919T070056, start_date=20230919T070057, end_date=20230919T070100
[2023-09-19T07:01:00.503+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task extract_data (Command '['/tmp/venvr_s49ypj/bin/pip', 'install', '-r', '/tmp/venvr_s49ypj/requirements.txt']' returned non-zero exit status 1.; 4370)
[2023-09-19T07:01:00.546+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T07:01:00.563+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
