[2023-09-19T09:57:49.222+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data.create_chart manual__2023-09-19T09:57:46.051421+00:00 [queued]>
[2023-09-19T09:57:49.226+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data.create_chart manual__2023-09-19T09:57:46.051421+00:00 [queued]>
[2023-09-19T09:57:49.227+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T09:57:49.233+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonVirtualenvOperator): create_chart> on 2023-09-19 09:57:46.051421+00:00
[2023-09-19T09:57:49.238+0000] {standard_task_runner.py:57} INFO - Started process 972 to run task
[2023-09-19T09:57:49.240+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'create_chart', 'manual__2023-09-19T09:57:46.051421+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpcvbf9h8y']
[2023-09-19T09:57:49.241+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask create_chart
[2023-09-19T09:57:49.273+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data.create_chart manual__2023-09-19T09:57:46.051421+00:00 [running]> on host 12ae14f8feaf
[2023-09-19T09:57:49.322+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data' AIRFLOW_CTX_TASK_ID='create_chart' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T09:57:46.051421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T09:57:46.051421+00:00'
[2023-09-19T09:57:49.324+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvv59q_7lp --system-site-packages
[2023-09-19T09:57:49.334+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T09:57:50.261+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 377ms
[2023-09-19T09:57:50.262+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvv59q_7lp, clear=False, no_vcs_ignore=False, global=True)
[2023-09-19T09:57:50.262+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-09-19T09:57:50.263+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.2, setuptools==68.0.0, wheel==0.40.0
[2023-09-19T09:57:50.263+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-09-19T09:57:50.295+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvv59q_7lp/bin/pip install -r /tmp/venvv59q_7lp/requirements.txt
[2023-09-19T09:57:50.316+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T09:57:51.540+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvv59q_7lp/requirements.txt (line 1)) (2.0.3)
[2023-09-19T09:57:51.943+0000] {process_utils.py:190} INFO - Collecting matplotlib (from -r /tmp/venvv59q_7lp/requirements.txt (line 2))
[2023-09-19T09:57:51.944+0000] {process_utils.py:190} INFO -   Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/84/76/9267af394cb88ce5245b5a9d328ee90ccd5710a1d08b0ec363c3a86cd992/matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T09:57:52.117+0000] {process_utils.py:190} INFO -   Downloading matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.7 kB)
[2023-09-19T09:57:52.167+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvv59q_7lp/requirements.txt (line 1)) (2.8.2)
[2023-09-19T09:57:52.167+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvv59q_7lp/requirements.txt (line 1)) (2023.3)
[2023-09-19T09:57:52.167+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvv59q_7lp/requirements.txt (line 1)) (2023.3)
[2023-09-19T09:57:52.168+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy>=1.20.3 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvv59q_7lp/requirements.txt (line 1)) (1.24.4)
[2023-09-19T09:57:52.292+0000] {process_utils.py:190} INFO - Collecting contourpy>=1.0.1 (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2))
[2023-09-19T09:57:52.292+0000] {process_utils.py:190} INFO -   Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/9b/cb/08f884c4c2efd433a38876b1b8069bfecef3f2d21ff0ce635d455962f70f/contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T09:57:52.341+0000] {process_utils.py:190} INFO -   Downloading contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.9 kB)
[2023-09-19T09:57:52.402+0000] {process_utils.py:190} INFO - Collecting cycler>=0.10 (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2))
[2023-09-19T09:57:52.452+0000] {process_utils.py:190} INFO -   Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
[2023-09-19T09:57:52.570+0000] {process_utils.py:190} INFO - Collecting fonttools>=4.22.0 (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2))
[2023-09-19T09:57:52.571+0000] {process_utils.py:190} INFO -   Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/61/3f/68c99c2b5fb29f42ba22027d035ae08f0b2ea0178fbf00e7cef730b1a809/fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T09:57:52.620+0000] {process_utils.py:190} INFO -   Downloading fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (150 kB)
[2023-09-19T09:57:52.701+0000] {process_utils.py:190} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.0/151.0 kB 1.9 MB/s eta 0:00:00
[2023-09-19T09:57:52.813+0000] {process_utils.py:190} INFO - Collecting kiwisolver>=1.0.1 (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2))
[2023-09-19T09:57:52.813+0000] {process_utils.py:190} INFO -   Obtaining dependency information for kiwisolver>=1.0.1 from https://files.pythonhosted.org/packages/10/15/0c225864a00eb3dbd3d04b6465f331dc12a6e80673449166457b9566036d/kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
[2023-09-19T09:57:52.865+0000] {process_utils.py:190} INFO -   Downloading kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.4 kB)
[2023-09-19T09:57:52.868+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging>=20.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2)) (23.1)
[2023-09-19T09:57:53.140+0000] {process_utils.py:190} INFO - Collecting pillow>=6.2.0 (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2))
[2023-09-19T09:57:53.142+0000] {process_utils.py:190} INFO -   Obtaining dependency information for pillow>=6.2.0 from https://files.pythonhosted.org/packages/2e/17/f19ad27effaf9b1ce6fe88d9f238d430293c486e33fdac71f037153cfd37/Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl.metadata
[2023-09-19T09:57:53.290+0000] {process_utils.py:190} INFO -   Downloading Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl.metadata (9.5 kB)
[2023-09-19T09:57:53.294+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2)) (3.1.1)
[2023-09-19T09:57:53.295+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources>=3.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2)) (6.0.1)
[2023-09-19T09:57:53.334+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=3.1.0 in /home/***/.local/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib->-r /tmp/venvv59q_7lp/requirements.txt (line 2)) (3.16.2)
[2023-09-19T09:57:53.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvv59q_7lp/requirements.txt (line 1)) (1.16.0)
[2023-09-19T09:57:53.410+0000] {process_utils.py:190} INFO - Downloading matplotlib-3.7.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.4 MB)
[2023-09-19T09:57:53.891+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 26.6 MB/s eta 0:00:00
[2023-09-19T09:57:53.939+0000] {process_utils.py:190} INFO - Downloading contourpy-1.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (285 kB)
[2023-09-19T09:57:53.951+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.8/285.8 kB 25.3 MB/s eta 0:00:00
[2023-09-19T09:57:54.006+0000] {process_utils.py:190} INFO - Downloading fonttools-4.42.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.5 MB)
[2023-09-19T09:57:54.157+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 30.1 MB/s eta 0:00:00
[2023-09-19T09:57:54.219+0000] {process_utils.py:190} INFO - Downloading kiwisolver-1.4.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.4 MB)
[2023-09-19T09:57:54.263+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 31.8 MB/s eta 0:00:00
[2023-09-19T09:57:54.317+0000] {process_utils.py:190} INFO - Downloading Pillow-10.0.1-cp38-cp38-manylinux_2_28_aarch64.whl (3.5 MB)
[2023-09-19T09:57:54.512+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 18.0 MB/s eta 0:00:00
[2023-09-19T09:57:57.028+0000] {process_utils.py:190} INFO - Installing collected packages: pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
[2023-09-19T09:57:58.704+0000] {process_utils.py:190} INFO - Successfully installed contourpy-1.1.1 cycler-0.11.0 fonttools-4.42.1 kiwisolver-1.4.5 matplotlib-3.7.3 pillow-10.0.1
[2023-09-19T09:57:58.892+0000] {process_utils.py:190} INFO - 
[2023-09-19T09:57:58.893+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2 -> 23.2.1
[2023-09-19T09:57:58.893+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-09-19T09:57:59.053+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvv59q_7lp/bin/python /tmp/venvv59q_7lp/script.py /tmp/venvv59q_7lp/script.in /tmp/venvv59q_7lp/script.out /tmp/venvv59q_7lp/string_args.txt /tmp/venvv59q_7lp/termination.log
[2023-09-19T09:57:59.060+0000] {process_utils.py:186} INFO - Output:
[2023-09-19T09:58:00.053+0000] {process_utils.py:190} INFO - [[34m2023-09-19T09:58:00.052+0000[0m] {[34mfont_manager.py:[0m1547} INFO[0m - generated new fontManager[0m
[2023-09-19T09:58:00.355+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2023-09-19T09:58:00.356+0000] {process_utils.py:190} INFO -   File "/tmp/venvv59q_7lp/script.py", line 52, in <module>
[2023-09-19T09:58:00.356+0000] {process_utils.py:190} INFO -     res = chart(*arg_dict["args"], **arg_dict["kwargs"])
[2023-09-19T09:58:00.356+0000] {process_utils.py:190} INFO -   File "/tmp/venvv59q_7lp/script.py", line 30, in chart
[2023-09-19T09:58:00.356+0000] {process_utils.py:190} INFO -     df = pd.read_csv('../files/weather.csv')
[2023-09-19T09:58:00.357+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
[2023-09-19T09:58:00.357+0000] {process_utils.py:190} INFO -     return _read(filepath_or_buffer, kwds)
[2023-09-19T09:58:00.357+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
[2023-09-19T09:58:00.358+0000] {process_utils.py:190} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-09-19T09:58:00.358+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
[2023-09-19T09:58:00.358+0000] {process_utils.py:190} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-09-19T09:58:00.358+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
[2023-09-19T09:58:00.359+0000] {process_utils.py:190} INFO -     self.handles = get_handle(
[2023-09-19T09:58:00.359+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
[2023-09-19T09:58:00.359+0000] {process_utils.py:190} INFO -     handle = open(
[2023-09-19T09:58:00.359+0000] {process_utils.py:190} INFO - FileNotFoundError: [Errno 2] No such file or directory: '../files/weather.csv'
[2023-09-19T09:58:00.539+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 602, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 463, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '../files/weather.csv'
[2023-09-19T09:58:00.541+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=weather_data, task_id=create_chart, execution_date=20230919T095746, start_date=20230919T095749, end_date=20230919T095800
[2023-09-19T09:58:00.549+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task create_chart (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '../files/weather.csv'; 972)
[2023-09-19T09:58:00.576+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T09:58:00.584+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
